version: 1
policy:
  pullRequests: public
tasks:
  $match:
    '(tasks_for == "github-pull-request" && event["action"] in ["opened","reopened","synchronize"])':
      taskId:
        $eval: as_slugid("pr_task")
      provisionerId: proj-misc
      workerType: ci
      payload:
        maxRunTime: 3600
        image: node
        command:
          - /bin/bash
          - '--login'
          - '-c'
          - >-
            git clone {{event.head.repo.url}} repo && cd repo && git config
            advice.detachedHead false && git checkout {{event.head.sha}} && npm
            install . && npm run lint && npm test
      metadata:
        name: Run tests and linter
        description: ''
        owner: '${event.sender.login}@users.noreply.github.com'
        source: '${event.repository.url}'
